// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.jogre.server.data;

public final class ProtoSchema {
  private ProtoSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class OutgoingMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use OutgoingMessage.newBuilder() to construct.
    private OutgoingMessage() {}
    
    private static final OutgoingMessage defaultInstance = new OutgoingMessage();
    public static OutgoingMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public OutgoingMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jogre.server.data.ProtoSchema.internal_static_javatests_OutgoingMessage_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jogre.server.data.ProtoSchema.internal_static_javatests_OutgoingMessage_fieldAccessorTable;
    }
    
    // required string payload = 1;
    private boolean hasPayload;
    private java.lang.String payload_ = "";
    public boolean hasPayload() { return hasPayload; }
    public java.lang.String getPayload() { return payload_; }
    
    // required int32 ackToken = 2;
    private boolean hasAckToken;
    private int ackToken_ = 0;
    public boolean hasAckToken() { return hasAckToken; }
    public int getAckToken() { return ackToken_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasPayload) return false;
      if (!hasAckToken) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasPayload()) {
        output.writeString(1, getPayload());
      }
      if (hasAckToken()) {
        output.writeInt32(2, getAckToken());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPayload());
      }
      if (hasAckToken()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getAckToken());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.jogre.server.data.ProtoSchema.OutgoingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.OutgoingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.OutgoingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.OutgoingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.OutgoingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.OutgoingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.OutgoingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.OutgoingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.jogre.server.data.ProtoSchema.OutgoingMessage prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.jogre.server.data.ProtoSchema.OutgoingMessage.newBuilder()
      private Builder() {}
      
      org.jogre.server.data.ProtoSchema.OutgoingMessage result = new org.jogre.server.data.ProtoSchema.OutgoingMessage();
      
      @Override
      protected org.jogre.server.data.ProtoSchema.OutgoingMessage internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.jogre.server.data.ProtoSchema.OutgoingMessage();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jogre.server.data.ProtoSchema.OutgoingMessage.getDescriptor();
      }
      
      public org.jogre.server.data.ProtoSchema.OutgoingMessage getDefaultInstanceForType() {
        return org.jogre.server.data.ProtoSchema.OutgoingMessage.getDefaultInstance();
      }
      
      public org.jogre.server.data.ProtoSchema.OutgoingMessage build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.jogre.server.data.ProtoSchema.OutgoingMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.jogre.server.data.ProtoSchema.OutgoingMessage buildPartial() {
        org.jogre.server.data.ProtoSchema.OutgoingMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jogre.server.data.ProtoSchema.OutgoingMessage) {
          return mergeFrom((org.jogre.server.data.ProtoSchema.OutgoingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jogre.server.data.ProtoSchema.OutgoingMessage other) {
        if (other == org.jogre.server.data.ProtoSchema.OutgoingMessage.getDefaultInstance()) return this;
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasAckToken()) {
          setAckToken(other.getAckToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setPayload(input.readString());
              break;
            }
            case 16: {
              setAckToken(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string payload = 1;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public java.lang.String getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(java.lang.String value) {
        result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = "";
        return this;
      }
      
      // required int32 ackToken = 2;
      public boolean hasAckToken() {
        return result.hasAckToken();
      }
      public int getAckToken() {
        return result.getAckToken();
      }
      public Builder setAckToken(int value) {
        result.hasAckToken = true;
        result.ackToken_ = value;
        return this;
      }
      public Builder clearAckToken() {
        result.hasAckToken = false;
        result.ackToken_ = 0;
        return this;
      }
    }
    
    static {
      org.jogre.server.data.ProtoSchema.getDescriptor();
    }
  }
  
  public static final class Property extends
      com.google.protobuf.GeneratedMessage {
    // Use Property.newBuilder() to construct.
    private Property() {}
    
    private static final Property defaultInstance = new Property();
    public static Property getDefaultInstance() {
      return defaultInstance;
    }
    
    public Property getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jogre.server.data.ProtoSchema.internal_static_javatests_Property_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jogre.server.data.ProtoSchema.internal_static_javatests_Property_fieldAccessorTable;
    }
    
    // required string key = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // required string value = 2;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasKey) return false;
      if (!hasValue) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      if (hasValue()) {
        output.writeString(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.jogre.server.data.ProtoSchema.Property parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Property parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Property parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Property parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Property parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Property parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Property parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Property parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.jogre.server.data.ProtoSchema.Property prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.jogre.server.data.ProtoSchema.Property.newBuilder()
      private Builder() {}
      
      org.jogre.server.data.ProtoSchema.Property result = new org.jogre.server.data.ProtoSchema.Property();
      
      @Override
      protected org.jogre.server.data.ProtoSchema.Property internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.jogre.server.data.ProtoSchema.Property();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jogre.server.data.ProtoSchema.Property.getDescriptor();
      }
      
      public org.jogre.server.data.ProtoSchema.Property getDefaultInstanceForType() {
        return org.jogre.server.data.ProtoSchema.Property.getDefaultInstance();
      }
      
      public org.jogre.server.data.ProtoSchema.Property build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.jogre.server.data.ProtoSchema.Property buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.jogre.server.data.ProtoSchema.Property buildPartial() {
        org.jogre.server.data.ProtoSchema.Property returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jogre.server.data.ProtoSchema.Property) {
          return mergeFrom((org.jogre.server.data.ProtoSchema.Property)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jogre.server.data.ProtoSchema.Property other) {
        if (other == org.jogre.server.data.ProtoSchema.Property.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              setValue(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = "";
        return this;
      }
      
      // required string value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = "";
        return this;
      }
    }
    
    static {
      org.jogre.server.data.ProtoSchema.getDescriptor();
    }
  }
  
  public static final class MessageBusState extends
      com.google.protobuf.GeneratedMessage {
    // Use MessageBusState.newBuilder() to construct.
    private MessageBusState() {}
    
    private static final MessageBusState defaultInstance = new MessageBusState();
    public static MessageBusState getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageBusState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jogre.server.data.ProtoSchema.internal_static_javatests_MessageBusState_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jogre.server.data.ProtoSchema.internal_static_javatests_MessageBusState_fieldAccessorTable;
    }
    
    // repeated .javatests.OutgoingMessage messageQueue = 1;
    private java.util.List<org.jogre.server.data.ProtoSchema.OutgoingMessage> messageQueue_ =
      java.util.Collections.emptyList();
    public java.util.List<org.jogre.server.data.ProtoSchema.OutgoingMessage> getMessageQueueList() {
      return messageQueue_;
    }
    public int getMessageQueueCount() { return messageQueue_.size(); }
    public org.jogre.server.data.ProtoSchema.OutgoingMessage getMessageQueue(int index) {
      return messageQueue_.get(index);
    }
    
    // repeated .javatests.Property connectionProperties = 2;
    private java.util.List<org.jogre.server.data.ProtoSchema.Property> connectionProperties_ =
      java.util.Collections.emptyList();
    public java.util.List<org.jogre.server.data.ProtoSchema.Property> getConnectionPropertiesList() {
      return connectionProperties_;
    }
    public int getConnectionPropertiesCount() { return connectionProperties_.size(); }
    public org.jogre.server.data.ProtoSchema.Property getConnectionProperties(int index) {
      return connectionProperties_.get(index);
    }
    
    // required string randomSecret = 3;
    private boolean hasRandomSecret;
    private java.lang.String randomSecret_ = "";
    public boolean hasRandomSecret() { return hasRandomSecret; }
    public java.lang.String getRandomSecret() { return randomSecret_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasRandomSecret) return false;
      for (org.jogre.server.data.ProtoSchema.OutgoingMessage element : getMessageQueueList()) {
        if (!element.isInitialized()) return false;
      }
      for (org.jogre.server.data.ProtoSchema.Property element : getConnectionPropertiesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (org.jogre.server.data.ProtoSchema.OutgoingMessage element : getMessageQueueList()) {
        output.writeMessage(1, element);
      }
      for (org.jogre.server.data.ProtoSchema.Property element : getConnectionPropertiesList()) {
        output.writeMessage(2, element);
      }
      if (hasRandomSecret()) {
        output.writeString(3, getRandomSecret());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.jogre.server.data.ProtoSchema.OutgoingMessage element : getMessageQueueList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      for (org.jogre.server.data.ProtoSchema.Property element : getConnectionPropertiesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      if (hasRandomSecret()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getRandomSecret());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.jogre.server.data.ProtoSchema.MessageBusState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.MessageBusState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.MessageBusState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.MessageBusState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.MessageBusState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.MessageBusState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.MessageBusState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.MessageBusState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.jogre.server.data.ProtoSchema.MessageBusState prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.jogre.server.data.ProtoSchema.MessageBusState.newBuilder()
      private Builder() {}
      
      org.jogre.server.data.ProtoSchema.MessageBusState result = new org.jogre.server.data.ProtoSchema.MessageBusState();
      
      @Override
      protected org.jogre.server.data.ProtoSchema.MessageBusState internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.jogre.server.data.ProtoSchema.MessageBusState();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jogre.server.data.ProtoSchema.MessageBusState.getDescriptor();
      }
      
      public org.jogre.server.data.ProtoSchema.MessageBusState getDefaultInstanceForType() {
        return org.jogre.server.data.ProtoSchema.MessageBusState.getDefaultInstance();
      }
      
      public org.jogre.server.data.ProtoSchema.MessageBusState build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.jogre.server.data.ProtoSchema.MessageBusState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.jogre.server.data.ProtoSchema.MessageBusState buildPartial() {
        if (result.messageQueue_ != java.util.Collections.EMPTY_LIST) {
          result.messageQueue_ =
            java.util.Collections.unmodifiableList(result.messageQueue_);
        }
        if (result.connectionProperties_ != java.util.Collections.EMPTY_LIST) {
          result.connectionProperties_ =
            java.util.Collections.unmodifiableList(result.connectionProperties_);
        }
        org.jogre.server.data.ProtoSchema.MessageBusState returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jogre.server.data.ProtoSchema.MessageBusState) {
          return mergeFrom((org.jogre.server.data.ProtoSchema.MessageBusState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jogre.server.data.ProtoSchema.MessageBusState other) {
        if (other == org.jogre.server.data.ProtoSchema.MessageBusState.getDefaultInstance()) return this;
        if (!other.messageQueue_.isEmpty()) {
          if (result.messageQueue_.isEmpty()) {
            result.messageQueue_ = new java.util.ArrayList<org.jogre.server.data.ProtoSchema.OutgoingMessage>();
          }
          result.messageQueue_.addAll(other.messageQueue_);
        }
        if (!other.connectionProperties_.isEmpty()) {
          if (result.connectionProperties_.isEmpty()) {
            result.connectionProperties_ = new java.util.ArrayList<org.jogre.server.data.ProtoSchema.Property>();
          }
          result.connectionProperties_.addAll(other.connectionProperties_);
        }
        if (other.hasRandomSecret()) {
          setRandomSecret(other.getRandomSecret());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.jogre.server.data.ProtoSchema.OutgoingMessage.Builder subBuilder = org.jogre.server.data.ProtoSchema.OutgoingMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMessageQueue(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.jogre.server.data.ProtoSchema.Property.Builder subBuilder = org.jogre.server.data.ProtoSchema.Property.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addConnectionProperties(subBuilder.buildPartial());
              break;
            }
            case 26: {
              setRandomSecret(input.readString());
              break;
            }
          }
        }
      }
      
      
      // repeated .javatests.OutgoingMessage messageQueue = 1;
      public java.util.List<org.jogre.server.data.ProtoSchema.OutgoingMessage> getMessageQueueList() {
        return java.util.Collections.unmodifiableList(result.messageQueue_);
      }
      public int getMessageQueueCount() {
        return result.getMessageQueueCount();
      }
      public org.jogre.server.data.ProtoSchema.OutgoingMessage getMessageQueue(int index) {
        return result.getMessageQueue(index);
      }
      public Builder setMessageQueue(int index, org.jogre.server.data.ProtoSchema.OutgoingMessage value) {
        result.messageQueue_.set(index, value);
        return this;
      }
      public Builder setMessageQueue(int index, org.jogre.server.data.ProtoSchema.OutgoingMessage.Builder builderForValue) {
        result.messageQueue_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMessageQueue(org.jogre.server.data.ProtoSchema.OutgoingMessage value) {
        if (result.messageQueue_.isEmpty()) {
          result.messageQueue_ = new java.util.ArrayList<org.jogre.server.data.ProtoSchema.OutgoingMessage>();
        }
        result.messageQueue_.add(value);
        return this;
      }
      public Builder addMessageQueue(org.jogre.server.data.ProtoSchema.OutgoingMessage.Builder builderForValue) {
        if (result.messageQueue_.isEmpty()) {
          result.messageQueue_ = new java.util.ArrayList<org.jogre.server.data.ProtoSchema.OutgoingMessage>();
        }
        result.messageQueue_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMessageQueue(
          java.lang.Iterable<? extends org.jogre.server.data.ProtoSchema.OutgoingMessage> values) {
        if (result.messageQueue_.isEmpty()) {
          result.messageQueue_ = new java.util.ArrayList<org.jogre.server.data.ProtoSchema.OutgoingMessage>();
        }
        super.addAll(values, result.messageQueue_);
        return this;
      }
      public Builder clearMessageQueue() {
        result.messageQueue_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .javatests.Property connectionProperties = 2;
      public java.util.List<org.jogre.server.data.ProtoSchema.Property> getConnectionPropertiesList() {
        return java.util.Collections.unmodifiableList(result.connectionProperties_);
      }
      public int getConnectionPropertiesCount() {
        return result.getConnectionPropertiesCount();
      }
      public org.jogre.server.data.ProtoSchema.Property getConnectionProperties(int index) {
        return result.getConnectionProperties(index);
      }
      public Builder setConnectionProperties(int index, org.jogre.server.data.ProtoSchema.Property value) {
        result.connectionProperties_.set(index, value);
        return this;
      }
      public Builder setConnectionProperties(int index, org.jogre.server.data.ProtoSchema.Property.Builder builderForValue) {
        result.connectionProperties_.set(index, builderForValue.build());
        return this;
      }
      public Builder addConnectionProperties(org.jogre.server.data.ProtoSchema.Property value) {
        if (result.connectionProperties_.isEmpty()) {
          result.connectionProperties_ = new java.util.ArrayList<org.jogre.server.data.ProtoSchema.Property>();
        }
        result.connectionProperties_.add(value);
        return this;
      }
      public Builder addConnectionProperties(org.jogre.server.data.ProtoSchema.Property.Builder builderForValue) {
        if (result.connectionProperties_.isEmpty()) {
          result.connectionProperties_ = new java.util.ArrayList<org.jogre.server.data.ProtoSchema.Property>();
        }
        result.connectionProperties_.add(builderForValue.build());
        return this;
      }
      public Builder addAllConnectionProperties(
          java.lang.Iterable<? extends org.jogre.server.data.ProtoSchema.Property> values) {
        if (result.connectionProperties_.isEmpty()) {
          result.connectionProperties_ = new java.util.ArrayList<org.jogre.server.data.ProtoSchema.Property>();
        }
        super.addAll(values, result.connectionProperties_);
        return this;
      }
      public Builder clearConnectionProperties() {
        result.connectionProperties_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string randomSecret = 3;
      public boolean hasRandomSecret() {
        return result.hasRandomSecret();
      }
      public java.lang.String getRandomSecret() {
        return result.getRandomSecret();
      }
      public Builder setRandomSecret(java.lang.String value) {
        result.hasRandomSecret = true;
        result.randomSecret_ = value;
        return this;
      }
      public Builder clearRandomSecret() {
        result.hasRandomSecret = false;
        result.randomSecret_ = "";
        return this;
      }
    }
    
    static {
      org.jogre.server.data.ProtoSchema.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_javatests_OutgoingMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_javatests_OutgoingMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_javatests_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_javatests_Property_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_javatests_MessageBusState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_javatests_MessageBusState_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\014schema.proto\022\tjavatests\"4\n\017OutgoingMes" +
      "sage\022\017\n\007payload\030\001 \002(\t\022\020\n\010ackToken\030\002 \002(\005\"" +
      "&\n\010Property\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"" +
      "\214\001\n\017MessageBusState\0220\n\014messageQueue\030\001 \003(" +
      "\0132\032.javatests.OutgoingMessage\0221\n\024connect" +
      "ionProperties\030\002 \003(\0132\023.javatests.Property" +
      "\022\024\n\014randomSecret\030\003 \002(\tB&\n\025org.jogre.serv" +
      "er.dataB\013ProtoSchemaH\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_javatests_OutgoingMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_javatests_OutgoingMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_javatests_OutgoingMessage_descriptor,
              new java.lang.String[] { "Payload", "AckToken", },
              org.jogre.server.data.ProtoSchema.OutgoingMessage.class,
              org.jogre.server.data.ProtoSchema.OutgoingMessage.Builder.class);
          internal_static_javatests_Property_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_javatests_Property_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_javatests_Property_descriptor,
              new java.lang.String[] { "Key", "Value", },
              org.jogre.server.data.ProtoSchema.Property.class,
              org.jogre.server.data.ProtoSchema.Property.Builder.class);
          internal_static_javatests_MessageBusState_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_javatests_MessageBusState_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_javatests_MessageBusState_descriptor,
              new java.lang.String[] { "MessageQueue", "ConnectionProperties", "RandomSecret", },
              org.jogre.server.data.ProtoSchema.MessageBusState.class,
              org.jogre.server.data.ProtoSchema.MessageBusState.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
