// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.jogre.server.data;

public final class ProtoSchema {
  private ProtoSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class GameInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use GameInfo.newBuilder() to construct.
    private GameInfo() {}
    
    private static final GameInfo defaultInstance = new GameInfo();
    public static GameInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jogre.server.data.ProtoSchema.internal_static_persistence_GameInfo_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jogre.server.data.ProtoSchema.internal_static_persistence_GameInfo_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // optional string game_key = 2;
    private boolean hasGameKey;
    private java.lang.String gameKey_ = "";
    public boolean hasGameKey() { return hasGameKey; }
    public java.lang.String getGameKey() { return gameKey_; }
    
    // optional string players = 3;
    private boolean hasPlayers;
    private java.lang.String players_ = "";
    public boolean hasPlayers() { return hasPlayers; }
    public java.lang.String getPlayers() { return players_; }
    
    // optional string results = 4;
    private boolean hasResults;
    private java.lang.String results_ = "";
    public boolean hasResults() { return hasResults; }
    public java.lang.String getResults() { return results_; }
    
    // optional int64 start_time = 5;
    private boolean hasStartTime;
    private long startTime_ = 0L;
    public boolean hasStartTime() { return hasStartTime; }
    public long getStartTime() { return startTime_; }
    
    // optional int64 end_time = 6;
    private boolean hasEndTime;
    private long endTime_ = 0L;
    public boolean hasEndTime() { return hasEndTime; }
    public long getEndTime() { return endTime_; }
    
    // optional string history = 7;
    private boolean hasHistory;
    private java.lang.String history_ = "";
    public boolean hasHistory() { return hasHistory; }
    public java.lang.String getHistory() { return history_; }
    
    // optional string score = 8;
    private boolean hasScore;
    private java.lang.String score_ = "";
    public boolean hasScore() { return hasScore; }
    public java.lang.String getScore() { return score_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt64(1, getId());
      }
      if (hasGameKey()) {
        output.writeString(2, getGameKey());
      }
      if (hasPlayers()) {
        output.writeString(3, getPlayers());
      }
      if (hasResults()) {
        output.writeString(4, getResults());
      }
      if (hasStartTime()) {
        output.writeInt64(5, getStartTime());
      }
      if (hasEndTime()) {
        output.writeInt64(6, getEndTime());
      }
      if (hasHistory()) {
        output.writeString(7, getHistory());
      }
      if (hasScore()) {
        output.writeString(8, getScore());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getId());
      }
      if (hasGameKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getGameKey());
      }
      if (hasPlayers()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPlayers());
      }
      if (hasResults()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getResults());
      }
      if (hasStartTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getStartTime());
      }
      if (hasEndTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, getEndTime());
      }
      if (hasHistory()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getHistory());
      }
      if (hasScore()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getScore());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.jogre.server.data.ProtoSchema.GameInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.jogre.server.data.ProtoSchema.GameInfo prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.jogre.server.data.ProtoSchema.GameInfo.newBuilder()
      private Builder() {}
      
      org.jogre.server.data.ProtoSchema.GameInfo result = new org.jogre.server.data.ProtoSchema.GameInfo();
      
      @Override
      protected org.jogre.server.data.ProtoSchema.GameInfo internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.jogre.server.data.ProtoSchema.GameInfo();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jogre.server.data.ProtoSchema.GameInfo.getDescriptor();
      }
      
      public org.jogre.server.data.ProtoSchema.GameInfo getDefaultInstanceForType() {
        return org.jogre.server.data.ProtoSchema.GameInfo.getDefaultInstance();
      }
      
      public org.jogre.server.data.ProtoSchema.GameInfo build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.jogre.server.data.ProtoSchema.GameInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.jogre.server.data.ProtoSchema.GameInfo buildPartial() {
        org.jogre.server.data.ProtoSchema.GameInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jogre.server.data.ProtoSchema.GameInfo) {
          return mergeFrom((org.jogre.server.data.ProtoSchema.GameInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jogre.server.data.ProtoSchema.GameInfo other) {
        if (other == org.jogre.server.data.ProtoSchema.GameInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasGameKey()) {
          setGameKey(other.getGameKey());
        }
        if (other.hasPlayers()) {
          setPlayers(other.getPlayers());
        }
        if (other.hasResults()) {
          setResults(other.getResults());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasHistory()) {
          setHistory(other.getHistory());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt64());
              break;
            }
            case 18: {
              setGameKey(input.readString());
              break;
            }
            case 26: {
              setPlayers(input.readString());
              break;
            }
            case 34: {
              setResults(input.readString());
              break;
            }
            case 40: {
              setStartTime(input.readInt64());
              break;
            }
            case 48: {
              setEndTime(input.readInt64());
              break;
            }
            case 58: {
              setHistory(input.readString());
              break;
            }
            case 66: {
              setScore(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // optional string game_key = 2;
      public boolean hasGameKey() {
        return result.hasGameKey();
      }
      public java.lang.String getGameKey() {
        return result.getGameKey();
      }
      public Builder setGameKey(java.lang.String value) {
        result.hasGameKey = true;
        result.gameKey_ = value;
        return this;
      }
      public Builder clearGameKey() {
        result.hasGameKey = false;
        result.gameKey_ = "";
        return this;
      }
      
      // optional string players = 3;
      public boolean hasPlayers() {
        return result.hasPlayers();
      }
      public java.lang.String getPlayers() {
        return result.getPlayers();
      }
      public Builder setPlayers(java.lang.String value) {
        result.hasPlayers = true;
        result.players_ = value;
        return this;
      }
      public Builder clearPlayers() {
        result.hasPlayers = false;
        result.players_ = "";
        return this;
      }
      
      // optional string results = 4;
      public boolean hasResults() {
        return result.hasResults();
      }
      public java.lang.String getResults() {
        return result.getResults();
      }
      public Builder setResults(java.lang.String value) {
        result.hasResults = true;
        result.results_ = value;
        return this;
      }
      public Builder clearResults() {
        result.hasResults = false;
        result.results_ = "";
        return this;
      }
      
      // optional int64 start_time = 5;
      public boolean hasStartTime() {
        return result.hasStartTime();
      }
      public long getStartTime() {
        return result.getStartTime();
      }
      public Builder setStartTime(long value) {
        result.hasStartTime = true;
        result.startTime_ = value;
        return this;
      }
      public Builder clearStartTime() {
        result.hasStartTime = false;
        result.startTime_ = 0L;
        return this;
      }
      
      // optional int64 end_time = 6;
      public boolean hasEndTime() {
        return result.hasEndTime();
      }
      public long getEndTime() {
        return result.getEndTime();
      }
      public Builder setEndTime(long value) {
        result.hasEndTime = true;
        result.endTime_ = value;
        return this;
      }
      public Builder clearEndTime() {
        result.hasEndTime = false;
        result.endTime_ = 0L;
        return this;
      }
      
      // optional string history = 7;
      public boolean hasHistory() {
        return result.hasHistory();
      }
      public java.lang.String getHistory() {
        return result.getHistory();
      }
      public Builder setHistory(java.lang.String value) {
        result.hasHistory = true;
        result.history_ = value;
        return this;
      }
      public Builder clearHistory() {
        result.hasHistory = false;
        result.history_ = "";
        return this;
      }
      
      // optional string score = 8;
      public boolean hasScore() {
        return result.hasScore();
      }
      public java.lang.String getScore() {
        return result.getScore();
      }
      public Builder setScore(java.lang.String value) {
        result.hasScore = true;
        result.score_ = value;
        return this;
      }
      public Builder clearScore() {
        result.hasScore = false;
        result.score_ = "";
        return this;
      }
    }
    
    static {
      org.jogre.server.data.ProtoSchema.getDescriptor();
    }
  }
  
  public static final class GameSummary extends
      com.google.protobuf.GeneratedMessage {
    // Use GameSummary.newBuilder() to construct.
    private GameSummary() {}
    
    private static final GameSummary defaultInstance = new GameSummary();
    public static GameSummary getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameSummary getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jogre.server.data.ProtoSchema.internal_static_persistence_GameSummary_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jogre.server.data.ProtoSchema.internal_static_persistence_GameSummary_fieldAccessorTable;
    }
    
    // required string game_key = 1;
    private boolean hasGameKey;
    private java.lang.String gameKey_ = "";
    public boolean hasGameKey() { return hasGameKey; }
    public java.lang.String getGameKey() { return gameKey_; }
    
    // required string username = 2;
    private boolean hasUsername;
    private java.lang.String username_ = "";
    public boolean hasUsername() { return hasUsername; }
    public java.lang.String getUsername() { return username_; }
    
    // optional int32 rating = 3;
    private boolean hasRating;
    private int rating_ = 0;
    public boolean hasRating() { return hasRating; }
    public int getRating() { return rating_; }
    
    // optional int32 wins = 4;
    private boolean hasWins;
    private int wins_ = 0;
    public boolean hasWins() { return hasWins; }
    public int getWins() { return wins_; }
    
    // optional int32 loses = 5;
    private boolean hasLoses;
    private int loses_ = 0;
    public boolean hasLoses() { return hasLoses; }
    public int getLoses() { return loses_; }
    
    // optional int32 draws = 6;
    private boolean hasDraws;
    private int draws_ = 0;
    public boolean hasDraws() { return hasDraws; }
    public int getDraws() { return draws_; }
    
    // optional int32 streak = 7;
    private boolean hasStreak;
    private int streak_ = 0;
    public boolean hasStreak() { return hasStreak; }
    public int getStreak() { return streak_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasGameKey) return false;
      if (!hasUsername) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasGameKey()) {
        output.writeString(1, getGameKey());
      }
      if (hasUsername()) {
        output.writeString(2, getUsername());
      }
      if (hasRating()) {
        output.writeInt32(3, getRating());
      }
      if (hasWins()) {
        output.writeInt32(4, getWins());
      }
      if (hasLoses()) {
        output.writeInt32(5, getLoses());
      }
      if (hasDraws()) {
        output.writeInt32(6, getDraws());
      }
      if (hasStreak()) {
        output.writeInt32(7, getStreak());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGameKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getGameKey());
      }
      if (hasUsername()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getUsername());
      }
      if (hasRating()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getRating());
      }
      if (hasWins()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getWins());
      }
      if (hasLoses()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getLoses());
      }
      if (hasDraws()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getDraws());
      }
      if (hasStreak()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, getStreak());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.jogre.server.data.ProtoSchema.GameSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.GameSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.jogre.server.data.ProtoSchema.GameSummary prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.jogre.server.data.ProtoSchema.GameSummary.newBuilder()
      private Builder() {}
      
      org.jogre.server.data.ProtoSchema.GameSummary result = new org.jogre.server.data.ProtoSchema.GameSummary();
      
      @Override
      protected org.jogre.server.data.ProtoSchema.GameSummary internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.jogre.server.data.ProtoSchema.GameSummary();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jogre.server.data.ProtoSchema.GameSummary.getDescriptor();
      }
      
      public org.jogre.server.data.ProtoSchema.GameSummary getDefaultInstanceForType() {
        return org.jogre.server.data.ProtoSchema.GameSummary.getDefaultInstance();
      }
      
      public org.jogre.server.data.ProtoSchema.GameSummary build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.jogre.server.data.ProtoSchema.GameSummary buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.jogre.server.data.ProtoSchema.GameSummary buildPartial() {
        org.jogre.server.data.ProtoSchema.GameSummary returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jogre.server.data.ProtoSchema.GameSummary) {
          return mergeFrom((org.jogre.server.data.ProtoSchema.GameSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jogre.server.data.ProtoSchema.GameSummary other) {
        if (other == org.jogre.server.data.ProtoSchema.GameSummary.getDefaultInstance()) return this;
        if (other.hasGameKey()) {
          setGameKey(other.getGameKey());
        }
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        if (other.hasWins()) {
          setWins(other.getWins());
        }
        if (other.hasLoses()) {
          setLoses(other.getLoses());
        }
        if (other.hasDraws()) {
          setDraws(other.getDraws());
        }
        if (other.hasStreak()) {
          setStreak(other.getStreak());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setGameKey(input.readString());
              break;
            }
            case 18: {
              setUsername(input.readString());
              break;
            }
            case 24: {
              setRating(input.readInt32());
              break;
            }
            case 32: {
              setWins(input.readInt32());
              break;
            }
            case 40: {
              setLoses(input.readInt32());
              break;
            }
            case 48: {
              setDraws(input.readInt32());
              break;
            }
            case 56: {
              setStreak(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string game_key = 1;
      public boolean hasGameKey() {
        return result.hasGameKey();
      }
      public java.lang.String getGameKey() {
        return result.getGameKey();
      }
      public Builder setGameKey(java.lang.String value) {
        result.hasGameKey = true;
        result.gameKey_ = value;
        return this;
      }
      public Builder clearGameKey() {
        result.hasGameKey = false;
        result.gameKey_ = "";
        return this;
      }
      
      // required string username = 2;
      public boolean hasUsername() {
        return result.hasUsername();
      }
      public java.lang.String getUsername() {
        return result.getUsername();
      }
      public Builder setUsername(java.lang.String value) {
        result.hasUsername = true;
        result.username_ = value;
        return this;
      }
      public Builder clearUsername() {
        result.hasUsername = false;
        result.username_ = "";
        return this;
      }
      
      // optional int32 rating = 3;
      public boolean hasRating() {
        return result.hasRating();
      }
      public int getRating() {
        return result.getRating();
      }
      public Builder setRating(int value) {
        result.hasRating = true;
        result.rating_ = value;
        return this;
      }
      public Builder clearRating() {
        result.hasRating = false;
        result.rating_ = 0;
        return this;
      }
      
      // optional int32 wins = 4;
      public boolean hasWins() {
        return result.hasWins();
      }
      public int getWins() {
        return result.getWins();
      }
      public Builder setWins(int value) {
        result.hasWins = true;
        result.wins_ = value;
        return this;
      }
      public Builder clearWins() {
        result.hasWins = false;
        result.wins_ = 0;
        return this;
      }
      
      // optional int32 loses = 5;
      public boolean hasLoses() {
        return result.hasLoses();
      }
      public int getLoses() {
        return result.getLoses();
      }
      public Builder setLoses(int value) {
        result.hasLoses = true;
        result.loses_ = value;
        return this;
      }
      public Builder clearLoses() {
        result.hasLoses = false;
        result.loses_ = 0;
        return this;
      }
      
      // optional int32 draws = 6;
      public boolean hasDraws() {
        return result.hasDraws();
      }
      public int getDraws() {
        return result.getDraws();
      }
      public Builder setDraws(int value) {
        result.hasDraws = true;
        result.draws_ = value;
        return this;
      }
      public Builder clearDraws() {
        result.hasDraws = false;
        result.draws_ = 0;
        return this;
      }
      
      // optional int32 streak = 7;
      public boolean hasStreak() {
        return result.hasStreak();
      }
      public int getStreak() {
        return result.getStreak();
      }
      public Builder setStreak(int value) {
        result.hasStreak = true;
        result.streak_ = value;
        return this;
      }
      public Builder clearStreak() {
        result.hasStreak = false;
        result.streak_ = 0;
        return this;
      }
    }
    
    static {
      org.jogre.server.data.ProtoSchema.getDescriptor();
    }
  }
  
  public static final class Snapshot extends
      com.google.protobuf.GeneratedMessage {
    // Use Snapshot.newBuilder() to construct.
    private Snapshot() {}
    
    private static final Snapshot defaultInstance = new Snapshot();
    public static Snapshot getDefaultInstance() {
      return defaultInstance;
    }
    
    public Snapshot getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jogre.server.data.ProtoSchema.internal_static_persistence_Snapshot_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jogre.server.data.ProtoSchema.internal_static_persistence_Snapshot_fieldAccessorTable;
    }
    
    // required string game_key = 1;
    private boolean hasGameKey;
    private java.lang.String gameKey_ = "";
    public boolean hasGameKey() { return hasGameKey; }
    public java.lang.String getGameKey() { return gameKey_; }
    
    // optional int32 num_of_users = 2;
    private boolean hasNumOfUsers;
    private int numOfUsers_ = 0;
    public boolean hasNumOfUsers() { return hasNumOfUsers; }
    public int getNumOfUsers() { return numOfUsers_; }
    
    // optional int32 num_of_tables = 3;
    private boolean hasNumOfTables;
    private int numOfTables_ = 0;
    public boolean hasNumOfTables() { return hasNumOfTables; }
    public int getNumOfTables() { return numOfTables_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasGameKey) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasGameKey()) {
        output.writeString(1, getGameKey());
      }
      if (hasNumOfUsers()) {
        output.writeInt32(2, getNumOfUsers());
      }
      if (hasNumOfTables()) {
        output.writeInt32(3, getNumOfTables());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGameKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getGameKey());
      }
      if (hasNumOfUsers()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getNumOfUsers());
      }
      if (hasNumOfTables()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getNumOfTables());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.jogre.server.data.ProtoSchema.Snapshot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Snapshot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Snapshot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Snapshot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Snapshot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Snapshot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.jogre.server.data.ProtoSchema.Snapshot prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.jogre.server.data.ProtoSchema.Snapshot.newBuilder()
      private Builder() {}
      
      org.jogre.server.data.ProtoSchema.Snapshot result = new org.jogre.server.data.ProtoSchema.Snapshot();
      
      @Override
      protected org.jogre.server.data.ProtoSchema.Snapshot internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.jogre.server.data.ProtoSchema.Snapshot();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jogre.server.data.ProtoSchema.Snapshot.getDescriptor();
      }
      
      public org.jogre.server.data.ProtoSchema.Snapshot getDefaultInstanceForType() {
        return org.jogre.server.data.ProtoSchema.Snapshot.getDefaultInstance();
      }
      
      public org.jogre.server.data.ProtoSchema.Snapshot build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.jogre.server.data.ProtoSchema.Snapshot buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.jogre.server.data.ProtoSchema.Snapshot buildPartial() {
        org.jogre.server.data.ProtoSchema.Snapshot returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jogre.server.data.ProtoSchema.Snapshot) {
          return mergeFrom((org.jogre.server.data.ProtoSchema.Snapshot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jogre.server.data.ProtoSchema.Snapshot other) {
        if (other == org.jogre.server.data.ProtoSchema.Snapshot.getDefaultInstance()) return this;
        if (other.hasGameKey()) {
          setGameKey(other.getGameKey());
        }
        if (other.hasNumOfUsers()) {
          setNumOfUsers(other.getNumOfUsers());
        }
        if (other.hasNumOfTables()) {
          setNumOfTables(other.getNumOfTables());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setGameKey(input.readString());
              break;
            }
            case 16: {
              setNumOfUsers(input.readInt32());
              break;
            }
            case 24: {
              setNumOfTables(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string game_key = 1;
      public boolean hasGameKey() {
        return result.hasGameKey();
      }
      public java.lang.String getGameKey() {
        return result.getGameKey();
      }
      public Builder setGameKey(java.lang.String value) {
        result.hasGameKey = true;
        result.gameKey_ = value;
        return this;
      }
      public Builder clearGameKey() {
        result.hasGameKey = false;
        result.gameKey_ = "";
        return this;
      }
      
      // optional int32 num_of_users = 2;
      public boolean hasNumOfUsers() {
        return result.hasNumOfUsers();
      }
      public int getNumOfUsers() {
        return result.getNumOfUsers();
      }
      public Builder setNumOfUsers(int value) {
        result.hasNumOfUsers = true;
        result.numOfUsers_ = value;
        return this;
      }
      public Builder clearNumOfUsers() {
        result.hasNumOfUsers = false;
        result.numOfUsers_ = 0;
        return this;
      }
      
      // optional int32 num_of_tables = 3;
      public boolean hasNumOfTables() {
        return result.hasNumOfTables();
      }
      public int getNumOfTables() {
        return result.getNumOfTables();
      }
      public Builder setNumOfTables(int value) {
        result.hasNumOfTables = true;
        result.numOfTables_ = value;
        return this;
      }
      public Builder clearNumOfTables() {
        result.hasNumOfTables = false;
        result.numOfTables_ = 0;
        return this;
      }
    }
    
    static {
      org.jogre.server.data.ProtoSchema.getDescriptor();
    }
  }
  
  public static final class User extends
      com.google.protobuf.GeneratedMessage {
    // Use User.newBuilder() to construct.
    private User() {}
    
    private static final User defaultInstance = new User();
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jogre.server.data.ProtoSchema.internal_static_persistence_User_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jogre.server.data.ProtoSchema.internal_static_persistence_User_fieldAccessorTable;
    }
    
    // required string username = 1;
    private boolean hasUsername;
    private java.lang.String username_ = "";
    public boolean hasUsername() { return hasUsername; }
    public java.lang.String getUsername() { return username_; }
    
    // optional string password = 2;
    private boolean hasPassword;
    private java.lang.String password_ = "";
    public boolean hasPassword() { return hasPassword; }
    public java.lang.String getPassword() { return password_; }
    
    // optional int32 security_question = 3;
    private boolean hasSecurityQuestion;
    private int securityQuestion_ = 0;
    public boolean hasSecurityQuestion() { return hasSecurityQuestion; }
    public int getSecurityQuestion() { return securityQuestion_; }
    
    // optional string security_answer = 4;
    private boolean hasSecurityAnswer;
    private java.lang.String securityAnswer_ = "";
    public boolean hasSecurityAnswer() { return hasSecurityAnswer; }
    public java.lang.String getSecurityAnswer() { return securityAnswer_; }
    
    // optional string year_of_birth = 5;
    private boolean hasYearOfBirth;
    private java.lang.String yearOfBirth_ = "";
    public boolean hasYearOfBirth() { return hasYearOfBirth; }
    public java.lang.String getYearOfBirth() { return yearOfBirth_; }
    
    // optional string email = 6;
    private boolean hasEmail;
    private java.lang.String email_ = "";
    public boolean hasEmail() { return hasEmail; }
    public java.lang.String getEmail() { return email_; }
    
    // optional bool receive_newsletter = 7;
    private boolean hasReceiveNewsletter;
    private boolean receiveNewsletter_ = false;
    public boolean hasReceiveNewsletter() { return hasReceiveNewsletter; }
    public boolean getReceiveNewsletter() { return receiveNewsletter_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasUsername) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasUsername()) {
        output.writeString(1, getUsername());
      }
      if (hasPassword()) {
        output.writeString(2, getPassword());
      }
      if (hasSecurityQuestion()) {
        output.writeInt32(3, getSecurityQuestion());
      }
      if (hasSecurityAnswer()) {
        output.writeString(4, getSecurityAnswer());
      }
      if (hasYearOfBirth()) {
        output.writeString(5, getYearOfBirth());
      }
      if (hasEmail()) {
        output.writeString(6, getEmail());
      }
      if (hasReceiveNewsletter()) {
        output.writeBool(7, getReceiveNewsletter());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasUsername()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUsername());
      }
      if (hasPassword()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPassword());
      }
      if (hasSecurityQuestion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getSecurityQuestion());
      }
      if (hasSecurityAnswer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSecurityAnswer());
      }
      if (hasYearOfBirth()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getYearOfBirth());
      }
      if (hasEmail()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getEmail());
      }
      if (hasReceiveNewsletter()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, getReceiveNewsletter());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.jogre.server.data.ProtoSchema.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jogre.server.data.ProtoSchema.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.jogre.server.data.ProtoSchema.User prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.jogre.server.data.ProtoSchema.User.newBuilder()
      private Builder() {}
      
      org.jogre.server.data.ProtoSchema.User result = new org.jogre.server.data.ProtoSchema.User();
      
      @Override
      protected org.jogre.server.data.ProtoSchema.User internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.jogre.server.data.ProtoSchema.User();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jogre.server.data.ProtoSchema.User.getDescriptor();
      }
      
      public org.jogre.server.data.ProtoSchema.User getDefaultInstanceForType() {
        return org.jogre.server.data.ProtoSchema.User.getDefaultInstance();
      }
      
      public org.jogre.server.data.ProtoSchema.User build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.jogre.server.data.ProtoSchema.User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.jogre.server.data.ProtoSchema.User buildPartial() {
        org.jogre.server.data.ProtoSchema.User returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jogre.server.data.ProtoSchema.User) {
          return mergeFrom((org.jogre.server.data.ProtoSchema.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jogre.server.data.ProtoSchema.User other) {
        if (other == org.jogre.server.data.ProtoSchema.User.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasSecurityQuestion()) {
          setSecurityQuestion(other.getSecurityQuestion());
        }
        if (other.hasSecurityAnswer()) {
          setSecurityAnswer(other.getSecurityAnswer());
        }
        if (other.hasYearOfBirth()) {
          setYearOfBirth(other.getYearOfBirth());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasReceiveNewsletter()) {
          setReceiveNewsletter(other.getReceiveNewsletter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setUsername(input.readString());
              break;
            }
            case 18: {
              setPassword(input.readString());
              break;
            }
            case 24: {
              setSecurityQuestion(input.readInt32());
              break;
            }
            case 34: {
              setSecurityAnswer(input.readString());
              break;
            }
            case 42: {
              setYearOfBirth(input.readString());
              break;
            }
            case 50: {
              setEmail(input.readString());
              break;
            }
            case 56: {
              setReceiveNewsletter(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required string username = 1;
      public boolean hasUsername() {
        return result.hasUsername();
      }
      public java.lang.String getUsername() {
        return result.getUsername();
      }
      public Builder setUsername(java.lang.String value) {
        result.hasUsername = true;
        result.username_ = value;
        return this;
      }
      public Builder clearUsername() {
        result.hasUsername = false;
        result.username_ = "";
        return this;
      }
      
      // optional string password = 2;
      public boolean hasPassword() {
        return result.hasPassword();
      }
      public java.lang.String getPassword() {
        return result.getPassword();
      }
      public Builder setPassword(java.lang.String value) {
        result.hasPassword = true;
        result.password_ = value;
        return this;
      }
      public Builder clearPassword() {
        result.hasPassword = false;
        result.password_ = "";
        return this;
      }
      
      // optional int32 security_question = 3;
      public boolean hasSecurityQuestion() {
        return result.hasSecurityQuestion();
      }
      public int getSecurityQuestion() {
        return result.getSecurityQuestion();
      }
      public Builder setSecurityQuestion(int value) {
        result.hasSecurityQuestion = true;
        result.securityQuestion_ = value;
        return this;
      }
      public Builder clearSecurityQuestion() {
        result.hasSecurityQuestion = false;
        result.securityQuestion_ = 0;
        return this;
      }
      
      // optional string security_answer = 4;
      public boolean hasSecurityAnswer() {
        return result.hasSecurityAnswer();
      }
      public java.lang.String getSecurityAnswer() {
        return result.getSecurityAnswer();
      }
      public Builder setSecurityAnswer(java.lang.String value) {
        result.hasSecurityAnswer = true;
        result.securityAnswer_ = value;
        return this;
      }
      public Builder clearSecurityAnswer() {
        result.hasSecurityAnswer = false;
        result.securityAnswer_ = "";
        return this;
      }
      
      // optional string year_of_birth = 5;
      public boolean hasYearOfBirth() {
        return result.hasYearOfBirth();
      }
      public java.lang.String getYearOfBirth() {
        return result.getYearOfBirth();
      }
      public Builder setYearOfBirth(java.lang.String value) {
        result.hasYearOfBirth = true;
        result.yearOfBirth_ = value;
        return this;
      }
      public Builder clearYearOfBirth() {
        result.hasYearOfBirth = false;
        result.yearOfBirth_ = "";
        return this;
      }
      
      // optional string email = 6;
      public boolean hasEmail() {
        return result.hasEmail();
      }
      public java.lang.String getEmail() {
        return result.getEmail();
      }
      public Builder setEmail(java.lang.String value) {
        result.hasEmail = true;
        result.email_ = value;
        return this;
      }
      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = "";
        return this;
      }
      
      // optional bool receive_newsletter = 7;
      public boolean hasReceiveNewsletter() {
        return result.hasReceiveNewsletter();
      }
      public boolean getReceiveNewsletter() {
        return result.getReceiveNewsletter();
      }
      public Builder setReceiveNewsletter(boolean value) {
        result.hasReceiveNewsletter = true;
        result.receiveNewsletter_ = value;
        return this;
      }
      public Builder clearReceiveNewsletter() {
        result.hasReceiveNewsletter = false;
        result.receiveNewsletter_ = false;
        return this;
      }
    }
    
    static {
      org.jogre.server.data.ProtoSchema.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_persistence_GameInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_persistence_GameInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_persistence_GameSummary_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_persistence_GameSummary_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_persistence_Snapshot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_persistence_Snapshot_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_persistence_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_persistence_User_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\014schema.proto\022\013persistence\"\220\001\n\010GameInfo" +
      "\022\n\n\002id\030\001 \002(\003\022\020\n\010game_key\030\002 \001(\t\022\017\n\007player" +
      "s\030\003 \001(\t\022\017\n\007results\030\004 \001(\t\022\022\n\nstart_time\030\005" +
      " \001(\003\022\020\n\010end_time\030\006 \001(\003\022\017\n\007history\030\007 \001(\t\022" +
      "\r\n\005score\030\010 \001(\t\"}\n\013GameSummary\022\020\n\010game_ke" +
      "y\030\001 \002(\t\022\020\n\010username\030\002 \002(\t\022\016\n\006rating\030\003 \001(" +
      "\005\022\014\n\004wins\030\004 \001(\005\022\r\n\005loses\030\005 \001(\005\022\r\n\005draws\030" +
      "\006 \001(\005\022\016\n\006streak\030\007 \001(\005\"I\n\010Snapshot\022\020\n\010gam" +
      "e_key\030\001 \002(\t\022\024\n\014num_of_users\030\002 \001(\005\022\025\n\rnum" +
      "_of_tables\030\003 \001(\005\"\240\001\n\004User\022\020\n\010username\030\001 " +
      "\002(\t\022\020\n\010password\030\002 \001(\t\022\031\n\021security_questi" +
      "on\030\003 \001(\005\022\027\n\017security_answer\030\004 \001(\t\022\025\n\ryea" +
      "r_of_birth\030\005 \001(\t\022\r\n\005email\030\006 \001(\t\022\032\n\022recei" +
      "ve_newsletter\030\007 \001(\010B&\n\025org.jogre.server." +
      "dataB\013ProtoSchemaH\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_persistence_GameInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_persistence_GameInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_persistence_GameInfo_descriptor,
              new java.lang.String[] { "Id", "GameKey", "Players", "Results", "StartTime", "EndTime", "History", "Score", },
              org.jogre.server.data.ProtoSchema.GameInfo.class,
              org.jogre.server.data.ProtoSchema.GameInfo.Builder.class);
          internal_static_persistence_GameSummary_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_persistence_GameSummary_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_persistence_GameSummary_descriptor,
              new java.lang.String[] { "GameKey", "Username", "Rating", "Wins", "Loses", "Draws", "Streak", },
              org.jogre.server.data.ProtoSchema.GameSummary.class,
              org.jogre.server.data.ProtoSchema.GameSummary.Builder.class);
          internal_static_persistence_Snapshot_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_persistence_Snapshot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_persistence_Snapshot_descriptor,
              new java.lang.String[] { "GameKey", "NumOfUsers", "NumOfTables", },
              org.jogre.server.data.ProtoSchema.Snapshot.class,
              org.jogre.server.data.ProtoSchema.Snapshot.Builder.class);
          internal_static_persistence_User_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_persistence_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_persistence_User_descriptor,
              new java.lang.String[] { "Username", "Password", "SecurityQuestion", "SecurityAnswer", "YearOfBirth", "Email", "ReceiveNewsletter", },
              org.jogre.server.data.ProtoSchema.User.class,
              org.jogre.server.data.ProtoSchema.User.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
